/* DO NOT EDIT THIS FILE - it is machine generated */
#include <C:\Program Files\Java\jdk-19\include\jni.h>
/* Header for class Mean */

#ifndef _Included_Mean
#define _Included_Mean
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mean
 * Method:    mean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Mean_mean
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
